import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header';
import HomePage from '../components/HomePage';
import Button from '../components/UI/Button';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage />
    </>
  );
};

export default Home;
